name: deeplink_x_web
description: "Web implementation of the deeplink_x plugin."
version: 0.0.2

repository: https://github.com/DeeplinkX/DeeplinkXWeb

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  deeplink_x_platform_interface: ^0.0.4
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  plugin:
    implements: deeplink_x
    platforms:
      web:
        dartPluginClass: LauncherUtilLinux
        fileName: "deeplink_x_web.dart"
        pluginClass: LauncherUtilWeb
